name: NFTArts
options:
  bundleIdPrefix: com.gorenkov
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "27LYLK4WV8"

targets:
  NFTArts:
    type: application
    platform: iOS
    sources:
      - path: NFTArts
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: NFTArts/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_BUNDLE_IDENTIFIER: com.gorenkov.NFTArts
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    resources:
      - path: NFTArts/Resources/Assets.xcassets
