[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
buildContext = "backend"

[deploy]
startCommand = "./App serve --env production --hostname 0.0.0.0"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
